name: icebrella_health
description: Your medicine reminder

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  # State management & persistence
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  hydrated_bloc: ^8.0.0
  ## Dep injection & Route management
  get_it: ^7.2.0
  flutter_modular: ^5.0.3
  ## UI
  flutter_slidable: ^2.0.0 # don't think I will use it in new design
  flutter_svg: ^1.1.1+1
  wheel_chooser: ^1.0.0
  badges: ^2.0.2
  smooth_page_indicator: ^1.0.0+2 # used for onboarding
  movin_icons: # purchased icons for ui, they are private
    git: https://github.com/onlymice/movin_icons.git
  # shimmer: ^2.0.0 will be used for shimmering effect at loading
  # responsive_framework: ^0.2.0 # I have some plans using it in further versions
  ## Utils
  path_provider: ^2.0.8
  measures: ^0.2.2
  equatable: ^2.0.3
  timeago: ^3.1.0 # TODO replace with custom intl (translatable timeago)
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  json_intl: ^2.0.0
  # Cupertino icons
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  # TODO decide on app's font 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
